parameters:
  cors.config:
    enabled: true
    allowedMethods:
      - "GET"
      - "POST"
      - "OPTIONS"
    allowedHeaders:
      - "Accept"
      - "Content-Type"
    allowedOrigins:
      - "hzswdef-wine.netlify.app"
